config/routes.rb
Rails.application.routes.draw do

  get '/deleted_tweets',   to: 'tweets#index'
  delete '/delete_tweet', to: 'tweets#destroy'

  get '/twitter_users', to: 'twitter_users#index'
  get '/twitter_users/:id', to: 'twitter_users#show', as: 'twitter_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  get  '/add_user', to: 'users#new'
  post '/add_user', to: 'users#create'
  resources :users, :except => [ :show ]

  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]
  
  match '*path', to: redirect("/"), via: :all

  #help_path -> /help
  #help_url  -> http://www.example.com
end

app/models/twitter_user.rb
class TwitterUser < ApplicationRecord
  has_many :tweets, foreign_key: :user_id
  has_many :deleted_tweets, -> { where(deleted: :true) }, 
           class_name: "Tweet", 
           foreign_key: :user_id

  validates :screen_name, :name, presence: true

  def self.find_or_save_user(user)
    find_or_create_by(user_id: user.id, 
                      screen_name: user.screen_name, 
                      name: user.name)
  end
end

app/controllers/twitter_users_controller.rb
require 'twitter_client'
require 'will_paginate/array'

class TwitterUsersController < ApplicationController

  def index
    @twitter_users = twitter_users_list
  end

  def show
    begin
      @user = parse_user_info(TwitterClient.client.user(params[:id].to_i))
    rescue Twitter::Error::NotFound => error
      Rails.logger.info "Unable to find user. Message: #{error.message}"
      flash[:danger] = "Unable to find user. UserID: params[:id]"
      redirect_to 'index'
      return
    end

    @deleted_tweets = Tweet.where(
      "user_id = ? and deleted = ? and text is not null", @user[:id], true)
    .order(deleted_at: :desc).paginate(page: params[:page], per_page: 20)
  end
  
  private
    def parse_user_info(user)
      parse_users_info([user]).first
    end

    def parse_users_info(users)
      result = []
      users.each do |user|
        h = {}
        h[:id]                = user.id.to_s
        h[:name]              = user.name
        h[:screen_name]       = user.screen_name
        h[:followers_count]   = user.followers_count
        h[:friends_count]     = user.friends_count
        h[:profile_image_url] = user.profile_image_url.to_s
        result << h
      end
      return result
    end

    def twitter_users_list
      client = TwitterClient.client

      if (session[:friend_ids].blank? || 
          session[:friend_ids_count] != client.user.friends_count)
        set_friend_ids_to_session(friend_ids_list_of(client))
      end

      users = client.users(session[:friend_ids]).unshift(client.user)
      parsed_users = parse_users_info(users)
      parsed_users.paginate(page: params[:page], per_page: 30)
    end

    def set_friend_ids_to_session(id_array)
      session[:friend_ids] = id_array
      session[:friend_ids_count] = id_array.count
    end

    def friend_ids_list_of(client)
      begin
        @friend_ids = client.friend_ids.to_a
      rescue Twitter::Error::TooManyRequests => error
        Rails.logger.info "Unable to get Twitter Users information '#{error.message}'"
        flash.now[:danger] = "Twitter Rate Limit Exceeded. Unable to retreive" +
                             "friends list at the moment."
      end

      @friend_ids || []
    end
end

app/helpers/twitter_users_helper.rb
module TwitterUsersHelper
  def bigger_image(url)
    url.gsub!("_normal", "_bigger")
  end

  def original_image(url)
    url.gsub!("_normal", "")
  end

  def deleted_tweet_count(user)
    Tweet.where({user_id: user[:id], deleted: true}).count
  end

  def recent_tweet_count(user)
    Tweet.where({user_id: user[:id]}).count
  end

  def last_tweeted_date_of(user)
    last_tweet = Tweet.where(user_id: user[:id]) .order(:created_at).last
    if last_tweet.present?
      "#{last_tweet.created_at.to_formatted_s(:db)} #{last_tweet.created_at.zone}"
    end
  end
end

app/views/twitter_users/_twitter_users.html.erb
<% twitter_users.each do |user| %>
  <div class="row list-group-item">
    <!-- Image -->
    <div class="col-lg-2 col-md-2 col-sm-3">
      <%= image_tag( bigger_image(user[:profile_image_url]), 
                    class: "img-rounded img-thumbnail img-responsive pull-right", 
                    size: 73 )%>
    </div>

    <!-- Twitter User Info -->
    <div class="col-lg-10 col-md-10 col-sm-9 twitter_user_info">
      <div class="row">
        <!-- Username - Screen Name -->
        <div class="col-lg-12">
          <h4 class="list-group-item-heading">
            <%= link_to user[:name], 
              "https://twitter.com/#{user[:screen_name]}", target: "_blank" %> 
            <small class="list-group-item-text">
              @<%= user[:screen_name] %>
            </small>
          </h4>
        </div>

        <!-- Follwer/Following count -->
        <div class="col-lg-8 col-md-8 col-sm-7">
          <p class="list-group-item-text">
            Followers: <%= user[:followers_count] %> | 
            Following: <%= user[:friends_count] %>
          </p>
        </div>

        <!-- Badges -->
        <div class="col-lg-4 col-md-4 col-sm-5 vcenter">
          <p class="list-group-item-text">
          <%= link_to twitter_user_path(user[:id]) do %>
            <span>Deleted </span>
          <% end %>
          <span class="badge alert-danger"><%= deleted_tweet_count(user) %></span>
          <span>/ Tweeted </span><span class="badge alert-success"><%= recent_tweet_count(user) %></span>
          </p>
        </div>

      </div><!-- END row -->
    </div> <!-- END Twitter User Info -->

  </div>
<% end %>

app/views/twitter_users/index.html.erb
<% provide(:title, "Twitter Users") %>
<h2 class="center">Twitter Users</h2>

<div class="row">
  <div class="container">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-xs-12">
      <div class="row"><%= will_paginate %></div>
      <div class="list-group">
          <%= render 'twitter_users', twitter_users: @twitter_users %> 
      </div>
      <div class="row"><%= will_paginate %></div>
    </div>
  </div>
</div>

app/views/twitter_users/show.html.erb
<% provide(:title, "Twitter Users") %>
<div class= "row">
  <div class= "col-lg-10 col-lg-offset-1">
    <div class="row">

      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="row">
          <p class="list-group-item-text">
            <%= image_tag( original_image(@user[:profile_image_url]),
                   class: "img-rounded img-thumbnail img-responsive",
                   size: 200)%>
         </p>
         <h3 class="">
           <%= link_to "#{fa_icon 'twitter'}#{@user[:name]}".html_safe, 
              "https://twitter.com/#{@user[:screen_name]}", target: "_blank" %> 
              <small class="">@<%= @user[:screen_name] %></small>
         </h3>

            <!-- Follwer/Following count -->
            <p class="list-group-item-text">
              Followers: <%= @user[:followers_count] %></p>
            <p class="list-group-item-text">
              Following: <%= @user[:friends_count] %></p>
            <p class="list-group-item-text">
              Deleted Tweets: <%= deleted_tweet_count(@user) %></p>
            <p class="list-group-item-text">
              Last Tweet: <%= last_tweeted_date_of(@user) %></p>
        </div>
      </div><!--4-->

      <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="row">
          <div class="col-lg-12">
            <div class="list-group">
							<div href="#" class="list-group-item row">
								<h4 class="list-group-item-heading center">
                  <span data-toggle="tooltip" data-placement="top" title="Only tweets with content will be displayed">Deleted Tweets
                    <%= fa_icon 'info-circle' %></span>
                </h4>
							</div>
              <div class="row"><%= will_paginate(@deleted_tweets) %></div>
              <%= render 'tweets/tweets', common_page: false, tweets: @deleted_tweets %>
              <div class="row"><%= will_paginate(@deleted_tweets) %></div>
            </div>
          </div>
        </div>
      </div><!--8-->

    </div><!--row -->
  </div><!-- col-lg-10 -->
</div><!-- row -->