config/routes.rb
Rails.application.routes.draw do

  get '/deleted_tweets',   to: 'tweets#index'
  delete '/delete_tweet', to: 'tweets#destroy'

  get '/twitter_users', to: 'twitter_users#index'
  get '/twitter_users/:id', to: 'twitter_users#show', as: 'twitter_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  get  '/add_user', to: 'users#new'
  post '/add_user', to: 'users#create'
  resources :users, :except => [ :show ]

  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]
  
  match '*path', to: redirect("/"), via: :all

  #help_path -> /help
  #help_url  -> http://www.example.com
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Twitter Observer for <a href="http://teyit.org">teyit.org</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
  <div class="container">
    <!-- Header-->
    <div class="navbar-header">
      <%= link_to "O_O", root_path, id: "logo", class: "navbar-brand" %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-contents">
        <span class="sr-only">Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Content-->
    <div class="collapse navbar-collapse" id="navbar-contents">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "Watch List", twitter_users_path %></il>
            <li><%= link_to "Deleted Tweets", deleted_tweets_path %></il>
            <li><%= link_to "Users", users_path %></il>
            <li><%= link_to "Add User", add_user_path %></il>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></il>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log Out", logout_path, method: :delete, 
                    class: "dropdown-item"%>
                 </il>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div><!-- Content -->
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "TwitterObserver" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>